"""initial_schema

Revision ID: 0710fe0c6475
Revises: 
Create Date: 2026-03-19 07:46:49.617440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0710fe0c6475'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'agents', 'admin_users', ['owner_id'], ['user_id'])
    op.alter_column('artifact_versions', 'version_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('artifact_versions', 'is_watermarked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('artifact_versions', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('artifact_versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_artifact_versions_artifact'), table_name='artifact_versions')
    op.drop_index(op.f('idx_artifact_versions_worker'), table_name='artifact_versions')
    op.create_index(op.f('ix_artifact_versions_artifact_id'), 'artifact_versions', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_versions_worker_id'), 'artifact_versions', ['worker_id'], unique=False)
    op.drop_constraint(None, 'artifact_versions', type_='foreignkey')
    op.create_foreign_key(None, 'artifact_versions', 'artifacts', ['artifact_id'], ['artifact_id'])
    op.alter_column('bids', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('bids', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('job_workers', 'id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('job_workers', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('job_workers', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('job_workers', 'is_winner',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('job_workers', 'credit_penalty',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('job_workers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('job_workers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_job_workers_job'), table_name='job_workers')
    op.drop_index(op.f('idx_job_workers_worker'), table_name='job_workers')
    op.create_index(op.f('ix_job_workers_job_id'), 'job_workers', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_workers_worker_id'), 'job_workers', ['worker_id'], unique=False)
    op.drop_constraint(None, 'job_workers', type_='foreignkey')
    op.create_foreign_key(None, 'job_workers', 'jobs', ['job_id'], ['job_id'])
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('jobs', 'deposit_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('jobs', 'final_payment_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.create_foreign_key(None, 'jobs', 'agents', ['winner_id'], ['agent_id'])
    op.alter_column('message_delivery', 'message_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('message_delivery', 'delivered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('message_delivery', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_message_delivery_delivered'), table_name='message_delivery')
    op.drop_index(op.f('idx_message_delivery_recipient'), table_name='message_delivery')
    op.create_index(op.f('ix_message_delivery_recipient_id'), 'message_delivery', ['recipient_id'], unique=False)
    op.alter_column('payments', 'payment_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('payments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_payments_job'), table_name='payments')
    op.drop_index(op.f('idx_payments_payee'), table_name='payments')
    op.drop_index(op.f('idx_payments_payer'), table_name='payments')
    op.create_index(op.f('ix_payments_job_id'), 'payments', ['job_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'jobs', ['job_id'], ['job_id'])
    op.drop_column('reputation_logs', 'job_id')
    op.alter_column('ws_connections', 'connection_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('ws_connections', 'connected_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_ws_connections_agent'), table_name='ws_connections')
    op.create_index(op.f('ix_ws_connections_agent_id'), 'ws_connections', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ws_connections_agent_id'), table_name='ws_connections')
    op.create_index(op.f('idx_ws_connections_agent'), 'ws_connections', ['agent_id'], unique=False)
    op.alter_column('ws_connections', 'connected_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('ws_connections', 'connection_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.add_column('reputation_logs', sa.Column('job_id', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_job_id'), table_name='payments')
    op.create_index(op.f('idx_payments_payer'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('idx_payments_payee'), 'payments', ['payee_id'], unique=False)
    op.create_index(op.f('idx_payments_job'), 'payments', ['job_id'], unique=False)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('payments', 'payment_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('ix_message_delivery_recipient_id'), table_name='message_delivery')
    op.create_index(op.f('idx_message_delivery_recipient'), 'message_delivery', ['recipient_id'], unique=False)
    op.create_index(op.f('idx_message_delivery_delivered'), 'message_delivery', ['recipient_id', 'delivered'], unique=False)
    op.alter_column('message_delivery', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('message_delivery', 'delivered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('message_delivery', 'message_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.alter_column('jobs', 'final_payment_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('jobs', 'deposit_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('jobs', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_constraint(None, 'job_workers', type_='foreignkey')
    op.create_foreign_key(None, 'job_workers', 'jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_job_workers_worker_id'), table_name='job_workers')
    op.drop_index(op.f('ix_job_workers_job_id'), table_name='job_workers')
    op.create_index(op.f('idx_job_workers_worker'), 'job_workers', ['worker_id'], unique=False)
    op.create_index(op.f('idx_job_workers_job'), 'job_workers', ['job_id'], unique=False)
    op.alter_column('job_workers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('job_workers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('job_workers', 'credit_penalty',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('job_workers', 'is_winner',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('job_workers', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('job_workers', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('job_workers', 'id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('bids', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bids', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'artifact_versions', type_='foreignkey')
    op.create_foreign_key(None, 'artifact_versions', 'artifacts', ['artifact_id'], ['artifact_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_artifact_versions_worker_id'), table_name='artifact_versions')
    op.drop_index(op.f('ix_artifact_versions_artifact_id'), table_name='artifact_versions')
    op.create_index(op.f('idx_artifact_versions_worker'), 'artifact_versions', ['worker_id'], unique=False)
    op.create_index(op.f('idx_artifact_versions_artifact'), 'artifact_versions', ['artifact_id'], unique=False)
    op.alter_column('artifact_versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('artifact_versions', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('artifact_versions', 'is_watermarked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('artifact_versions', 'version_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.alter_column('agents', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('agents', 'deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###