"""Initial tables

Revision ID: 60c268102f26
Revises: 
Create Date: 2026-03-13 22:12:22.120356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c268102f26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'admin'"))
    op.alter_column('admin_users', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('admin_users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint(None, 'admin_users', ['username'])
    op.alter_column('agents', 'agent_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('agents', 'capabilities',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'idle'"))
    op.alter_column('agents', 'rating',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('agents', 'completed_jobs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('agents', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_agents_status'), table_name='agents')
    op.drop_index(op.f('idx_agents_type'), table_name='agents')
    op.alter_column('artifacts', 'artifact_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('artifacts', 'attachments',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('artifacts', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('artifacts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bids', 'bid_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('bids', 'quote_currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('bids', 'portfolio_links',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('bids', 'is_hired',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bids', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('bids', 'submitted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_bids_job'), table_name='bids')
    op.drop_index(op.f('idx_bids_status'), table_name='bids')
    op.drop_index(op.f('idx_bids_worker'), table_name='bids')
    op.alter_column('jobs', 'job_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('jobs', 'required_tags',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('jobs', 'currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'CNY'"))
    op.alter_column('jobs', 'deadline',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('jobs', 'bid_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('jobs', 'priority',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'normal'"))
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'OPEN'"))
    op.alter_column('jobs', 'selected_worker_ids',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('jobs', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('jobs', 'closed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_jobs_employer'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_status'), table_name='jobs')
    op.alter_column('messages', 'message_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'text'"))
    op.alter_column('messages', 'attachments',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('messages', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_messages_job'), table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_messages_job'), 'messages', ['job_id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('messages', 'attachments',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'text'"))
    op.alter_column('messages', 'message_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('idx_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('idx_jobs_employer'), 'jobs', ['employer_id'], unique=False)
    op.alter_column('jobs', 'closed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('jobs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('jobs', 'selected_worker_ids',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'OPEN'"))
    op.alter_column('jobs', 'priority',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'normal'"))
    op.alter_column('jobs', 'bid_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('jobs', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('jobs', 'currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'CNY'"))
    op.alter_column('jobs', 'required_tags',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('jobs', 'job_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('idx_bids_worker'), 'bids', ['worker_id'], unique=False)
    op.create_index(op.f('idx_bids_status'), 'bids', ['status'], unique=False)
    op.create_index(op.f('idx_bids_job'), 'bids', ['job_id'], unique=False)
    op.alter_column('bids', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bids', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('bids', 'is_hired',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bids', 'portfolio_links',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('bids', 'quote_currency',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('bids', 'bid_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('artifacts', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('artifacts', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('artifacts', 'attachments',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('artifacts', 'artifact_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('artifacts', 'artifact_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('idx_agents_type'), 'agents', ['agent_type'], unique=False)
    op.create_index(op.f('idx_agents_status'), 'agents', ['status'], unique=False)
    op.alter_column('agents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('agents', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('agents', 'completed_jobs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agents', 'rating',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'idle'"))
    op.alter_column('agents', 'capabilities',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('agents', 'agent_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(None, 'admin_users', type_='unique')
    op.alter_column('admin_users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('admin_users', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'admin'"))
    op.alter_column('admin_users', 'user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
